name: CI Testing
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: cypress:included
    steps:
     # - name: Prep Dependancies
     #   run: sudo apt install xvfb -y
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Add Vue/CLI
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: global add @vue/cli
      - name: Yarn Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Run End-to-End Tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:e2e:headless
