name: CI Testing
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Add Vue/CLI
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: global add @vue/cli
      - name: Yarn Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Run End-to-End Tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:e2e
